In [64]:
import pandas as pd
import numpy as np
from io import StringIO

In [65]:
data = pd.read_csv("new_qm9.csv")

In [66]:
data

,Unnamed: 0,properties,smiles,df_atoms
0,0,"['gdb', '35176', '3.69951', '1.23093', '1.0970...",N#CC1NC11C2CC1C2,Element X Y Z Ch...
1,1,"['gdb', '131462', '3.58161', '1.13798', '0.872...",OC1=NON=C1OC=O,Element X Y Z Ch...
2,2,"['gdb', '73123', '2.35658', '1.75261', '1.5222...",CC12CCC1CN1CC21,Element X Y Z Ch...
3,3,"['gdb', '96811', '2.20077', '1.50794', '0.9289...",CN=C1OC(=O)CC1N,Element X Y Z Ch...
4,4,"['gdb', '100867', '2.43658', '1.01176', '0.748...",CC(CO)C(CO)C#N,Element X Y Z Ch...
...,...,...,...,...
133656,133656,"['gdb', '89928', '3.2485', '1.28504', '1.09041...",CC1CC2(OCC12)C#C,Element X Y Z Ch...
133657,133657,"['gdb', '54585', '2.64598', '1.56716', '1.1822...",CC(=O)C12CCC1CO2,Element X Y Z Ch...
133658,133658,"['gdb', '65980', '2.69486', '1.28575', '1.1613...",CC1(CNC1=O)C1CN1,Element X Y Z Ch...
133659,133659,"['gdb', '74655', '4.57035', '1.41266', '1.2469...",CC1=NC2C3CC2C3O1,Element X Y Z Ch...
133660,133660,"['gdb', '32600', '2.68668', '1.25658', '0.9215...",CCN1C=C(O)N=C1C,Element X Y Z Ch...

In [67]:
data.drop(columns=["Unnamed: 0"], inplace=True)

In [68]:
data

,properties,smiles,df_atoms
0,"['gdb', '35176', '3.69951', '1.23093', '1.0970...",N#CC1NC11C2CC1C2,Element X Y Z Ch...
1,"['gdb', '131462', '3.58161', '1.13798', '0.872...",OC1=NON=C1OC=O,Element X Y Z Ch...
2,"['gdb', '73123', '2.35658', '1.75261', '1.5222...",CC12CCC1CN1CC21,Element X Y Z Ch...
3,"['gdb', '96811', '2.20077', '1.50794', '0.9289...",CN=C1OC(=O)CC1N,Element X Y Z Ch...
4,"['gdb', '100867', '2.43658', '1.01176', '0.748...",CC(CO)C(CO)C#N,Element X Y Z Ch...
...,...,...,...
133656,"['gdb', '89928', '3.2485', '1.28504', '1.09041...",CC1CC2(OCC12)C#C,Element X Y Z Ch...
133657,"['gdb', '54585', '2.64598', '1.56716', '1.1822...",CC(=O)C12CCC1CO2,Element X Y Z Ch...
133658,"['gdb', '65980', '2.69486', '1.28575', '1.1613...",CC1(CNC1=O)C1CN1,Element X Y Z Ch...
133659,"['gdb', '74655', '4.57035', '1.41266', '1.2469...",CC1=NC2C3CC2C3O1,Element X Y Z Ch...
133660,"['gdb', '32600', '2.68668', '1.25658', '0.9215...",CCN1C=C(O)N=C1C,Element X Y Z Ch...

## Extracting the properties

In [69]:
properties = data.iloc[:, 0]

In [70]:
s = properties[1]
s = s.strip("[").strip("]")
df = pd.read_csv(StringIO(s), header=None)
df = df.map(lambda x: x.replace("'", "") if isinstance(x, str) else x)
df.drop(columns=[0], inplace=True)
display(df)

,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
0,131462,3.58161,1.13798,0.87264,2.5256,55.4,-0.2868,-0.0597,0.2271,1180.5099,0.064339,-525.78337,-525.775913,-525.774969,-525.816245,25.955

## Extracting smiles

In [71]:
df["smiles"] = data["smiles"]

## Extracting Coordinates

In [72]:
c = data["df_atoms"][0]
c = c.split("\n")
c = c[1:-1]
c

['0        N -0.115821 -1.158881  0.025388 -0.337520',
 '1        C -0.063476 -0.003814  0.037201  0.335786',
 '2        C  0.011072  1.436089  0.006055 -0.351511',
 '3        N  0.587216  2.098087  1.224155 -0.401810',
 '4        C  1.306648  2.157246 -0.019118  0.488704',
 '5        C  2.756983  1.750274 -0.311638 -0.120940',
 '6        C  2.485500  2.228762 -1.772474 -0.215041',
 '7        C  1.836563  3.323016 -0.867790 -0.150471',
 '8        C  3.122209  3.233583  0.019031 -0.223719',
 '9        H -0.840285  1.911957 -0.473963  0.133233',
 '10       H  0.072043  2.956719  1.409329  0.243830',
 '11       H  3.268646  0.846385  0.013173  0.100189',
 '12       H  3.364665  2.545343 -2.337509  0.102145',
 '13       H  1.810674  1.619184 -2.377477  0.106847',
 '14       H  1.299431  4.218872 -1.181392  0.081344',
 '15       H  3.029506  3.542110  1.062340  0.108438']

In [83]:
atom_rows = []
for line in c:
    parts = line.split()
    if len(parts) >= 6:
        atom_rows.append(parts[1:6])  # atom, x, y, z, charge

atom_df = pd.DataFrame(atom_rows, columns=["atom", "x", "y", "z", "charge"])
atom_df[["x", "y", "z", "charge"]] = atom_df[["x", "y", "z", "charge"]].astype(float)
atom_df

   atom         x         y         z    charge
0     N -0.115821 -1.158881  0.025388 -0.337520
1     C -0.063476 -0.003814  0.037201  0.335786
2     C  0.011072  1.436089  0.006055 -0.351511
3     N  0.587216  2.098087  1.224155 -0.401810
4     C  1.306648  2.157246 -0.019118  0.488704
5     C  2.756983  1.750274 -0.311638 -0.120940
6     C  2.485500  2.228762 -1.772474 -0.215041
7     C  1.836563  3.323016 -0.867790 -0.150471
8     C  3.122209  3.233583  0.019031 -0.223719
9     H -0.840285  1.911957 -0.473963  0.133233
10    H  0.072043  2.956719  1.409329  0.243830
11    H  3.268646  0.846385  0.013173  0.100189
12    H  3.364665  2.545343 -2.337509  0.102145
13    H  1.810674  1.619184 -2.377477  0.106847
14    H  1.299431  4.218872 -1.181392  0.081344
15    H  3.029506  3.542110  1.062340  0.108438